### ISSUE TITLE
non-ascii unicode errors

### ISSUE THREAD

**Issue by clach04** [baruchel/txt2pdf#31]
The current code opens files in text/character mode NOT binary. This essentially means the encoding parameter is ignored.

Smallest test case is a text file that contains a non-ascii character like U+2013 and encoding in something non-utf8, e.g. latin1 (cp1252). See attached [latin1_hypen.txt](https://github.com/baruchel/txt2pdf/files/11182143/latin1_hypen.txt)

Sample output under Windows with python 2 and python 3:

### Python 2 Microsoft Windows

    C:\code\py\txt2pdf_clach04>py -2 txt2pdf.py --encoding latin1  latin1_hypen.txt
    Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
    Writing 'latin1_hypen.txt' with 80 characters per line and 60 lines per page...
    PDF document: 1 pages

### Python 3 Microsoft Windows

    C:\code\py\txt2pdf_clach04>py -3 txt2pdf.py --encoding latin1  latin1_hypen.txt
    Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
    Writing 'latin1_hypen.txt' with 80 characters per line and 60 lines per page...
    Traceback (most recent call last):
      File "txt2pdf.py", line 435, in <module>
        sys.exit(main())
      File "txt2pdf.py", line 429, in main
        args.margin_bottom)).generate()
      File "txt2pdf.py", line 214, in generate
        pageno = self._generatePlain(self._readDocument())
      File "txt2pdf.py", line 225, in _generatePlain
        for _, line in data:
      File "txt2pdf.py", line 176, in _readDocument
        for done, lineno, line in self._process(data):
      File "txt2pdf.py", line 163, in _process
        read += len(line.encode(self.encoding))
    UnicodeEncodeError: 'latin-1' codec can't encode character '\u2013' in position 54: ordinal not in range(256)

similar under Linux. Note potential for UnicodeDecodeError instead of UnicodeEncodeError.

PR (https://github.com/baruchel/txt2pdf/pull/32) posted, the main approach of the proposed fix is to use binary mode for the file and retaining the byte approadh already in place for `_process()`. An alternative would be to use codecs at file open time, but this is a more intrusive change and preserving the logic of the existing binary mode code has the potential to allow future changes for alternative encodings to be tried rather than a single one.

**Comment by clach04** [comment]
Posted https://github.com/baruchel/txt2pdf/pull/32
